name: ammp-influxdb
version: '1.7.8'
base: core18
summary: An Open-Source Time Series Database
description: |
  InfluxDB is an open source time series database with no external dependencies.
  It's useful for recording metrics, events, and performing analytics.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf

parts:
  wrapper-scripts:
    plugin: dump
    source: bin
    organize:
      runinfluxd.sh: bin/runinfluxd.sh
      initdb.sh: bin/initdb.sh
  influxdb:
    source: https://github.com/influxdata/influxdb.git
    source-tag: v1.7.8
    build-snaps: ["go"]
    source-depth: 1
    plugin: python
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/bin:$PATH"
      export GOPATH=$(readlink -f $(pwd)/../go)
      export GOIMPORTPATH=$GOPATH/src/github.com/influxdata/influxdb/
      mkdir -p $GOIMPORTPATH
      cp -r ./* $GOIMPORTPATH
      cp -r .git $GOIMPORTPATH
      cd $GOIMPORTPATH
      python build.py --outdir $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/conf
      cp etc/config.sample.toml $SNAPCRAFT_PART_INSTALL/conf/influxdb.conf
    stage-packages:
      - libdb5.3-dev
    build-packages: 
      - software-properties-common
      - wget
      - git
      - mercurial
      - make
      - ruby
      - ruby-dev
      - autoconf
      - libtool
      - build-essential
      - rpm
      - zip
      - python
      - python-boto
      - asciidoc
      - xmlto
      - docbook-xsl


apps:
  influx:
    command: bin/influx
    plugs:
      - network
  influxd:
    command: bin/runinfluxd.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network
  initdb:
    command: bin/initdb.sh
    daemon: oneshot
    plugs:
      - network
    after:
      - influxd

plugs:
  provisioning-influx:
    interface: content
    content: ammp-influx-provisioning
    target: $SNAP/provisioning